### ISSUE TITLE
AMD module support

### ISSUE THREAD

**Issue by KKSzymanowski** [rmariuzzo/Lang.js#33] opened 2016-10-15 18:24 UTC
Hi.

I kinda cannot get your package to work, maybe you can help me.

When I do
```js
var Lang = require('lang.js')

var lang = new Lang({
    messages: {
        "en.foo": {
            bar: 'baz'
        },
        "pl.foo": {
            bar: 'quz'
        }
    },
    locale: 'pl',
    fallback: 'en'
})
```
I get an error saying
```
Uncaught TypeError: Lang is not a constructor
```

Same thing happens when I replace `require` with `import`:
```js
import Lang from 'lang.js';
```

After import/require the Lang object looks like this:
```js
{
    locale: "en", 
    fallback: undefined, 
    messages: undefined
}
```

### Setup

Dependencies
```js
{
    "gulp": "^3.9.1",
    "gulp-shell": "^0.5.2",
    "jquery": "^3.1.0",
    "lang.js": "^1.1.1",
    "laravel-echo": "^1.1.0",
    "laravel-elixir": "^6.0.0-11",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    // and other like Vue or Moment.js    
}
```
gulpfile.js
```js
const elixir = require('laravel-elixir');
const shell = require('gulp-shell');

require('laravel-elixir-vue-2');

var Task = elixir.Task;
elixir.extend('langjs', function(path) {
    new Task('langjs', function() {
        gulp.src('').pipe(shell('php artisan lang:js resources/assets/js/messages.js'));
    });
});

elixir(mix => {
    mix.sass('app.scss')
        .langjs()
        .webpack('app.js')

});

```

**Comment by rmariuzzo** [comment] 2016-10-15 18:29
Hey @KKSzymanowski! Thanks for notifying me about this, I will check it later today.

**Comment by KKSzymanowski** [comment] 2016-10-15 21:41
Thanks. It's probably some misconfiguration on my end.

**Comment by KKSzymanowski** [comment] 2016-10-17 09:19
How is it going? Did you locate the issue origin? Maybe I can help you in some way.

**Comment by kaidoj** [comment] 2016-10-17 11:36
Im waiting this to be fixed also. I have the same issue. Using laravel,elixir,webpack.

**Comment by rmariuzzo** [comment] 2016-10-17 16:08
Hi @KKSzymanowski  / @kaidoj !

I'm checking this issue right now. I have tried to replicate the bug, but I can't. I did the following:

```sh
mkdir lang-js-test
cd lang-js-test
npm init
npm install --save lang.js@^1.1.1
node test.js
```

The contents of `test.js` is:

```js
var Lang = require('lang.js')

var lang = new Lang({
    messages: {
        "en.foo": {
            bar: 'baz'
        },
        "pl.foo": {
            bar: 'quz'
        }
    },
    locale: 'pl',
    fallback: 'en'
})

console.log(lang);
```

My version of node and NPM are:

```sh
$ npm version
{ 'lang-js-test': '1.0.0',
  npm: '3.10.5',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.3.1',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.57',
  zlib: '1.2.8' }
```

What are yours?

**Comment by KKSzymanowski** [comment] 2016-10-17 18:00
The example you provided does work, the `npm version` output is the same as yours.
I created a simple example to show the error.

It is a fresh Laravel 5.3 app with following files changed:
- `.gitignore` Removed `.env` from ignored files.
- `.env` Added an application key.
- `resources/assets/js/app.js` Added the example you provided.
- `resources/views/welcome.blade.php` Include script.

To install run following commands. It will take some time to download all npm and composer dependencies if you haven't them cached.
```
git clone https://github.com/kkszymanowski/lang-js-test
cd lang-js-test
npm install
composer update
gulp
php artisan serve
```
Then open `localhost:8000` in the browser and in the dev console you should see the error.

**Comment by rmariuzzo** [comment] 2016-10-17 18:05
Great @KKSzymanowski I'm running the commands.

**Comment by rmariuzzo** [comment] 2016-10-17 18:17
Reproduced, I'm checking right now.

**Comment by rmariuzzo** [comment] 2016-10-17 18:56
I could reproduce the issue. I'm analyzing the cause.

**Comment by rmariuzzo** [comment] 2016-10-17 19:00
Found the issue... working on a fix right now which I will explain.

**Comment by rmariuzzo** [comment] 2016-10-17 21:25
This will be released in a couple of mins.

**Closed** 2016-10-17 21:25 UTC
Labels: bug

**Comment by rmariuzzo** [comment] 2016-10-17 21:33
Released: https://github.com/rmariuzzo/Lang.js/releases/tag/v1.1.3

**Comment by jartaud** [comment] 2016-10-18 06:12
Uncaught TypeError: Lang is not a constructor using require/import

**Comment by KKSzymanowski** [comment] 2016-10-18 11:09
@jartaud Didn't work for me yesterday,because npm downloaded 1.1.2. Today I forced 1.1.3 and it works.

Thank you @rmariuzzo.

**Comment by rmariuzzo** [comment] 2016-10-18 11:13
@KKSzymanowski thank you for validate. 

@jartaud can you try with 1.1.3 and give us more details.

**Comment by jartaud** [comment] 2016-10-20 05:09
@KKSzymanowski, @rmariuzzo thank you guys. I was just trying to import the build generated by `php artisan lang:js -c`. I use [Translation manager for Laravel 5](https://github.com/PhiloNL/laravel-translate) and Lang.js for the win.
